version: "3.9"

services:

  mysql:
    image: tebancito/ims_mysql:latest
    container_name: ims_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
    restart: always

  web:
    image: tebancito/ims_cc:latest
    container_name: ims_web
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: inventario_db
    ports:
      - "8090:80"
    restart: always